{% set name = "azure-purview-workflow" %}
{% set version = "1.0.0b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/azure-purview-workflow-{{ version }}.zip
  sha256: e55559a414e80b4e196ff3295b2c7ad2a2bbbb6502156631512297b7f694beb4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - isodate <1.0.0,>=0.6.1
    - azure-core <2.0.0,>=1.24.0
    - typing-extensions >=4.3.0

test:
  imports:
    - azure.purview.workflow
    - azure.purview.workflow._operations
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk
  summary: Microsoft Azure Purview Workflow Service Client Library for Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - redur
